// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MaquinaEstado.DB.Model;

public partial class Estados
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public DateTime Creado { get; set; }

    public string CreadoPor { get; set; }

    public DateTime? Modificado { get; set; }

    public string ModificadoPor { get; set; }

    public bool Activo { get; set; }

    public virtual ICollection<HistorialEstados> HistorialEstadosEstadoAnterior { get; set; } = new List<HistorialEstados>();

    public virtual ICollection<HistorialEstados> HistorialEstadosEstadoNuevo { get; set; } = new List<HistorialEstados>();

    public virtual ICollection<Solicitudes> Solicitudes { get; set; } = new List<Solicitudes>();

    public virtual ICollection<Transiciones> TransicionesEstadoDestino { get; set; } = new List<Transiciones>();

    public virtual ICollection<Transiciones> TransicionesEstadoOrigen { get; set; } = new List<Transiciones>();
}