// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MaquinaEstado.DB.Model;

public partial class HistorialEstados
{
    public int Id { get; set; }

    public int SolicitudId { get; set; }

    public int EstadoAnteriorId { get; set; }

    public int EstadoNuevoId { get; set; }

    public string Usuario { get; set; }

    public DateTime FechaCambio { get; set; }

    public DateTime Creado { get; set; }

    public string CreadoPor { get; set; }

    public DateTime? Modificado { get; set; }

    public string ModificadoPor { get; set; }

    public bool Activo { get; set; }

    public virtual Estados EstadoAnterior { get; set; }

    public virtual Estados EstadoNuevo { get; set; }

    public virtual Solicitudes Solicitud { get; set; }
}