// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MaquinaEstado.DB.Model;

public partial class Solicitudes
{
    public int Id { get; set; }

    public string Descripcion { get; set; }

    public int EstadoId { get; set; }

    public DateTime Creado { get; set; }

    public string CreadoPor { get; set; }

    public DateTime? Modificado { get; set; }

    public string ModificadoPor { get; set; }

    public bool Activo { get; set; }

    public virtual Estados Estado { get; set; }

    public virtual ICollection<HistorialEstados> HistorialEstados { get; set; } = new List<HistorialEstados>();
}