// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MaquinaEstado.DB.Model;

public partial class Transiciones
{
    public int Id { get; set; }

    public int EstadoOrigenId { get; set; }

    public int EstadoDestinoId { get; set; }

    public DateTime Creado { get; set; }

    public string CreadoPor { get; set; }

    public DateTime? Modificado { get; set; }

    public string ModificadoPor { get; set; }

    public bool Activo { get; set; }

    public virtual Estados EstadoDestino { get; set; }

    public virtual Estados EstadoOrigen { get; set; }
}